### ISSUE TITLE
Underscore on Line #246

### ISSUE THREAD

**Issue by longoria** [frankpf/gridless-boilerplate#11]
Is there supposed to be an underscore prefixing the width style on line #246

``` css
img, object, embed, video {
    max-width: 100%; /* Consider this first: unstoppablerobotninja.com/entry/fluid-images/ */
    _width: 100%; /* If the image/video is smaller than the container, change 100% to an absolute value */
}
```
